services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb+srv://anjunarnolia99_db_user:fCAZeBrK1DuPZWxV@my-cluster.bkiiqah.mongodb.net/?appName=my-cluster
      JWT_SECRET: your_secret_key_change_in_production
      NODE_ENV: development
    depends_on:
      - mongo
    networks:
      - a-networks
    hostname: backend
    restart: always

  frontend:
    build:
      context: ./my-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - a-networks
    environment:
      VITE_API_URL: http://localhost:5000
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - a-networks
    environment:
      MONGO_INITDB_DATABASE: snippets
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  a-networks:
    driver: bridge

volumes:
  mongo_data:
